version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user
    
hooks:
  ApplicationStop:
    - location: Scripts/kill_process.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/run_process.sh
      timeout: 300
      runas: root
